services:
  - type: web
    name: platinum-optimizer-homi
    runtime: python
    plan: free
    region: oregon
    branch: main
    autoDeployTrigger: commit
    buildCommand: python -m py_compile server.py
    startCommand: python server.py
    healthCheckPath: /
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: OWNER_USERNAME
        value: homidark
      - key: OWNER_PASSWORD
        sync: false